- name: install haproxy
  package:
    name: haproxy

- name: set selinux conf
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  when: ansible_os_family == "RedHat"

- name: copy haproxy config
  copy:
    content: "{{ haproxy_config }}"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: add firewall ports
  firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: enabled
    zone: "{{ item.zone }}"
  notify: [ "firewalld" ]
  loop: "{{ haproxy_firewalld_ports }}"
  when: haproxy_firewalld_ports is defined
