- name: install haproxy
  package:
    name: haproxy

- name: set selinux conf
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  when: ansible_os_family == "RedHat"

- name: copy haproxy config
  copy:
    content: "{{ haproxy_config }}"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
